import React from 'react'
import './styles/TermsAndConditions.scss'

const TermsAndConditions = () => {
    return (
        <div className='termsandconditions'>

            <h1>Terms and Conditions</h1>

            <p><b>Last Updated:</b>21/4/2024</p>

            <div className='intro'>
                <p>
                    Welcome to TechLord! These Terms and Conditions govern your use of our e-commerce website, which includes the sale of devices and accessories, user-generated content, provision of technological information, and AI assistant support. By using our Website, you agree to these Terms. If you do not agree to these Terms, please do not use our Website.
                </p>
            </div>

            <div className="terms">
                <ol>
                    <li>
                        <h4>Account Registration</h4>
                        <ul>
                            <li>You must create an account to make purchases, sell items, or access certain features of the Website.</li>
                            <li>You are responsible for maintaining the confidentiality of your account information and password.</li>
                            <li>You must provide accurate and complete information during registration.</li>
                        </ul>

                    </li>

                    <li>
                        <h4>Purchasing</h4>
                        <ul>
                            <li>All prices and product descriptions are subject to change without notice.</li>
                            <li>Payment must be made at the time of purchase.</li>
                            <li>We reserve the right to refuse or cancel orders at our discretion.</li>
                        </ul>
                    </li>

                    <li>
                        <h4>Selling</h4>
                        <ul>

                            <li>You may list your own devices for sale on our Website in accordance with our selling guidelines.</li>
                            <li>You are responsible for the accuracy and legality of your listings.</li>
                            <li>We may remove listings that violate our policies or applicable laws.</li>
                        </ul>
                    </li>

                    <li>
                        <h4>Returns and Refunds</h4>
                        <ul>
                            {/* <li>Here's our Refund Policy</li> */}
                            <li>Returns must be made within the specified time frame and in original condition.</li>
                            <li>Refunds will be processed in accordance with our return policy.</li>
                        </ul>
                    </li>

                    <li>
                        <h4>User-Generated Content</h4>
                        <ul>
                            <li>You may submit reviews, comments, and other content on the Website.</li>
                            <li>By submitting content, you grant us a non-exclusive, worldwide, royalty-free license to use, display, and distribute your content.</li>
                            <li>We reserve the right to remove content that violates our policies.</li>
                        </ul>
                    </li>

                    <li>

                        <h4>Technological Information</h4>
                        <ul>
                            <li>The technological information provided on our Website is for general informational purposes only.</li>
                            <li>We do not guarantee the accuracy, completeness, or reliability of the information.</li>
                        </ul>
                    </li>

                    <li>
                        <h4>AI Assistant Support</h4>

                        <ul>
                            <li>Our AI assistant is provided to help you navigate the Website and answer general questions.</li>
                            <li>The AI assistant's responses are generated by algorithms and may not always be accurate.</li>
                            <li>We are not responsible for any decisions made based on the AI assistant's responses.</li>
                        </ul>
                    </li>

                    <li>

                        <h4>Privacy</h4>
                        <ul>
                            {/* <li>Our Privacy Policy is available [here] [Link to Privacy Policy].</li> */}
                            <li>By using the Website, you consent to the collection and use of your data as described in the Privacy Policy.</li>
                        </ul>
                    </li>

                    <li>

                        <h4>Intellectual Property</h4>

                        <ul>
                            <li>All content on the Website, including text, images, and graphics, is our property or the property of third parties and is protected by copyright and other intellectual property laws.</li>
                            <li>You may not reproduce, distribute, or create derivative works from our content without our prior written consent.</li>
                        </ul>
                    </li>

                    <li>

                        <h4>Limitation of Liability</h4>
                        <ul>
                            <li>We are not liable for any damages arising from your use of the Website, including direct, indirect, incidental, or consequential damages.</li>
                            <li>This limitation of liability does not apply where prohibited by law.</li>
                        </ul>
                    </li>

                    <li>
                        <h4>Governing Law</h4>
                        <ul>
                            <li>These Terms are governed by the laws of UT of Jammu and Kashmir.</li>
                            <li>Any disputes arising from your use of the Website will be subject to the exclusive jurisdiction of the courts in [Your Jurisdiction].</li>
                        </ul>
                    </li>

                    <li>

                        <h4>Changes to the Terms</h4>

                        <ul>
                            <li>We reserve the right to update these Terms at any time without notice.</li>
                            <li>By continuing to use the Website, you agree to the updated Terms.</li>
                        </ul>
                    </li>

                </ol>

            </div>

            {/* <div className="end">
                If you have any questions about these Terms and Conditions, please contact us at [Contact Information].

            </div> */}
        </div>
    )
}

export default TermsAndConditions